"""empty message

Revision ID: 4333684c9b45
Revises: a588af5d55ec
Create Date: 2024-05-19 14:53:21.727289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4333684c9b45'
down_revision = 'a588af5d55ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('created_at')
        batch_op.drop_column('about')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
